### ISSUE TITLE
Hint-Depth-Texture not supported.

### ISSUE THREAD

**Issue by Wardius** [eldskald/godot4-cel-shader#2]
Hey there, I noticed an error for Godot 4.2.stable in the 'refraction.gdshaderinc' file.
It says "'hint_depth_texture' is not supported in '' shaders"

I encountered this while I tried to implement a silhouette or x-ray shader together with your cel-shader. I can't get it working and I think it is because of this error.

<img width="961" alt="Bildschirmfoto 2024-02-12 um 11 47 20" src="https://github.com/eldskald/godot4-cel-shader/assets/84527236/f2794c3d-a50d-4aee-be36-081b2dde58ea">

**Comment by eldskald** [comment]
Hey there, thanks for the report. I checked it out and yes, there is this error but the shader seems to work as intended. I also looked at the docs and yes, `hint_depth_texture` is supported. Maybe this error is a bug, because materials using it seems to be working normally.

**Comment by Wardius** [comment]
Thanks for looking into it so quickly :)
I thought that error was the reason why I couldn't get the silhouette shader to work. Seems like I have to look into it a bit more!
